name: Deploy to Aliyun ECS

on:
  push:
    branches:
      - main  # 如果您的主分支是 master，请修改这里

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ALIYUN_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.ALIYUN_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to ECS
        run: |
          # 创建部署目录（如果不存在）
          ssh ${{ secrets.ALIYUN_USERNAME }}@${{ secrets.ALIYUN_HOST }} "mkdir -p /var/www/gomoku"
          
          # 复制文件到服务器
          scp -r ./* ${{ secrets.ALIYUN_USERNAME }}@${{ secrets.ALIYUN_HOST }}:/var/www/gomoku/
          
          # 设置权限
          ssh ${{ secrets.ALIYUN_USERNAME }}@${{ secrets.ALIYUN_HOST }} "cd /var/www/gomoku && chmod -R 755 ."
